# Generated by Django 4.2.3 on 2023-07-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todo_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='email',
            new_name='user_id',
        ),
    ]
